name: Build and Deploy on AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create back-end .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_PORT: ${{secrets.PORT}}
          envkey_POSTGRES_USERNAME: ${{secrets.POSTGRES_USERNAME}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          envkey_POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          envkey_DATABASE_URL: ${{secrets.DATABASE_URL}}
          directory: back-end
          file_name: .env
          fail_on_empty: true

      - name: Create front-end .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_VITE_APP_BACKEND_URL: ${{secrets.VITE_APP_BACKEND_URL}}
          directory: front-end
          file_name: .env
          fail_on_empty: true

      - name: Stop active containers
        run: docker compose down

      - name: Delete react_volume if it exists
        run: if docker volume ls --quiet --filter name=password-generator_react-volume | grep -q .; then docker volume rm password-generator_react-volume; fi

      - name: Build new images
        run: docker compose build

      - name: Start containers
        run: docker compose up -d